baseURL = 'https://dewaldv.com/'
languageCode = 'en-GB'
title = 'DEWALD VILJOEN'
copyright = 'Dewald Viljoen'

theme = "tales"

[params]
  mainSections = ["posts"]
  description = "A blog about Linux, Rust, homelabbing, and life as a developer."
  author = "Dewald Viljoen"
  github = "https://github.com/DewaldV"
  linkedin = "https://www.linkedin.com/in/dewaldv/"
  email = "dv@dewaldv.com"

[menu]
  [[menu.main]]
  identifier = "about"
  name = "ABOUT"
  url = "/about/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "POSTS"
  url = "/posts/"
  weight = 2
